export const vehicles = [
  { id: 1, name: 'Audi A5 Cabriolet', meta: '3.0 V6 TDI 245ch S line quattro S tronic 7', year: '2012', km: '259 897 km', fuel: 'Diesel', gearbox: 'Automatique', price: '11 990 €', tag: 'Nouveauté', status: 'Disponible', image: '/vehicles/audi-a5-front.jpg', gallery: ['/vehicles/audi-a5-front.jpg', '/vehicles/audi-a5-dashboard.jpg', '/vehicles/audi-a5-rear-seats.jpg', '/vehicles/audi-a5-exterior.jpg'], details: [['Marque','AUDI'],['Modèle','A5'],['Année modèle','2012'],['Kilométrage','259 897 km'],['Énergie','Diesel'],['Boîte de vitesse','Automatique'],['Nombre de portes','2'],['Nombre de places','4'],['Finition','S line'],['Couleur','Gris'],['Puissance DIN','245 Ch'],['Référence','1147']] },
  { id: 2, name: 'Peugeot 3008', meta: '1.5 BlueHDi 130 GT Line', year: '2020', km: '64 800 km', fuel: 'Diesel', gearbox: 'Automatique', price: '21 490 €', tag: 'Nouveauté', status: 'Disponible', image: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=1200&q=85', gallery: [] },
  { id: 3, name: 'Renault Clio V', meta: 'TCe 90 Intens', year: '2022', km: '28 150 km', fuel: 'Essence', gearbox: 'Manuelle', price: '15 490 €', tag: 'Bon plan', status: 'Disponible', image: 'https://images.unsplash.com/photo-1542282088-fe8426682b8f?auto=format&fit=crop&w=1200&q=85', gallery: [] },
  { id: 4, name: 'Citroën DS3', meta: '1.6 e-HDi 90 AirDream So Chic 5CV', year: '2012', km: '221 072 km', fuel: 'Diesel', gearbox: 'Manuelle', price: '4 990 €', tag: 'Bon plan', status: 'Disponible', image: '/vehicles/citroen-ds3-front.jpg', gallery: ['/vehicles/citroen-ds3-front.jpg', '/vehicles/citroen-ds3-rear.jpg', '/vehicles/citroen-ds3-interior.jpg', '/vehicles/citroen-ds3-rear-seats.jpg', '/vehicles/citroen-ds3-trunk.jpg', '/vehicles/citroen-ds3-exterior.jpg'], details: [['Marque','CITROËN'],['Modèle','DS3'],['Année modèle','2012'],['Kilométrage','221 072 km'],['Énergie','Diesel'],['Boîte de vitesse','Manuelle'],['Nombre de portes','3'],['Nombre de places','5'],['Finition','So Chic'],['Couleur','Marron'],['Puissance DIN','90 Ch'],['Référence','1226']] },
  { id: 5, name: 'Seat Ateca', meta: '2.0 TDI 150ch S&S Style Business DSG', year: '2020', km: '198 789 km', fuel: 'Diesel', gearbox: 'Automatique', price: '13 990 €', tag: 'Nouveauté', status: 'Disponible', image: '/vehicles/seat-ateca-front.jpg', gallery: ['/vehicles/seat-ateca-front.jpg', '/vehicles/seat-ateca-rear.jpg', '/vehicles/seat-ateca-dashboard.jpg', '/vehicles/seat-ateca-gallery.jpg'], details: [['Marque','SEAT'],['Modèle','Ateca'],['Année modèle','2020'],['Kilométrage','198 789 km'],['Énergie','Diesel'],['Boîte de vitesse','Automatique'],['Nombre de portes','5'],['Nombre de places','5'],['Finition','Style Business'],['Couleur','Blanc'],['Puissance DIN','150 Ch'],['Référence','1226']] },
  { id: 6, name: 'Peugeot 3008', meta: '1.6 BlueHDi 120ch Allure S&S', year: '2017', km: '272 694 km', fuel: 'Diesel', gearbox: 'Manuelle', price: '7 990 €', tag: 'Nouveauté', status: 'Disponible', image: '/vehicles/peugeot-3008-allure-front.jpg', gallery: ['/vehicles/peugeot-3008-allure-front.jpg', '/vehicles/peugeot-3008-allure-exterior.jpg', '/vehicles/peugeot-3008-allure-interior.jpg'], details: [['Marque','PEUGEOT'],['Modèle','3008'],['Année modèle','2017'],['Kilométrage','272 694 km'],['Énergie','Diesel'],['Boîte de vitesse','Manuelle'],['Nombre de portes','5'],['Nombre de places','5'],['Finition','Allure'],['Couleur','Gris'],['Puissance DIN','120 Ch'],['Référence','1226']] },
  { id: 7, name: 'Renault Mégane IV', meta: '1.5 Blue dCi 115ch Business EDC -21N', year: '2022', km: '142 762 km', fuel: 'Diesel', gearbox: 'Automatique', price: '12 490 €', tag: 'Nouveauté', status: 'Disponible', image: '/vehicles/renault-megane-front.jpg', gallery: ['/vehicles/renault-megane-front.jpg', '/vehicles/renault-megane-rear.jpg', '/vehicles/renault-megane-dashboard.jpg', '/vehicles/renault-megane-rear-seats.jpg', '/vehicles/renault-megane-exterior.jpg'], details: [['Marque','RENAULT'],['Modèle','Mégane'],['Année modèle','2022'],['Kilométrage','142 762 km'],['Énergie','Diesel'],['Boîte de vitesse','Automatique'],['Nombre de portes','5'],['Nombre de places','5'],['Finition','Business'],['Couleur','Gris'],['Puissance DIN','115 Ch'],['Référence','1149']] },
] as const
export type Vehicle = (typeof vehicles)[number]
export function getVehicle(id: string) { return vehicles.find((vehicle) => vehicle.id === Number(id)) }
