import { notFound } from 'next/navigation'
import { ArrowLeft, CalendarDays, ChevronLeft, ChevronRight, ShieldCheck } from 'lucide-react'
import Link from 'next/link'
import { getVehicle } from '@/lib/vehicles'

export default async function VehicleDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const vehicle = getVehicle((await params).id)
  if (!vehicle) notFound()
  const gallery = vehicle.gallery.length ? vehicle.gallery : [vehicle.image]
  return <main className="vehicle-showroom"><div className="vehicle-showroom-nav"><Link href="/vehicules"><ArrowLeft size={16} /> Retour aux véhicules</Link><span>Réf. {vehicle.details?.find(([label]) => label === 'Référence')?.[1] ?? vehicle.id}</span></div><div className="vehicle-showroom-layout"><section className="vehicle-gallery"><div className="vehicle-main-photo"><img src={gallery[0]} alt={`${vehicle.name} ${vehicle.meta}`} /><button aria-label="Photo précédente"><ChevronLeft /></button><button aria-label="Photo suivante"><ChevronRight /></button></div><div className="vehicle-thumbnails">{gallery.map((image, index) => <img key={image} src={image} alt={`${vehicle.name}, photo ${index + 1}`} />)}</div></section><aside className="vehicle-purchase"><span className="vehicle-status">{vehicle.status}</span><h1>{vehicle.name}</h1><p className="vehicle-version">{vehicle.meta}</p><strong className="showroom-price">{vehicle.price}</strong><p className="showroom-location">Saint-Jean-de-Védas · {vehicle.year} · {vehicle.km} · {vehicle.fuel}</p><Link className="button button-red showroom-cta" href="/contact">Contacter Planète Auto <CalendarDays size={17} /></Link><div className="showroom-trust"><ShieldCheck size={20} /><span><b>Garantie Planète Auto</b><br />Véhicule contrôlé et préparé avant livraison.</span></div></aside></div><section className="vehicle-facts"><div className="section-heading"><div><div className="eyebrow"><span className="eyebrow-line" /> Les informations clés</div><h2>Tout savoir sur<br /><em>ce véhicule.</em></h2></div></div><div className="facts-grid">{vehicle.details?.map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="vehicle-description"><h2>Description</h2><p>Audi A5 Cabriolet 3.0 V6 TDI 245ch S line quattro S tronic 7, coupé gris, 4 places, intérieur cuir et alcantara. Un véhicule entretenu et préparé avec soin par Planète Auto.</p></div></section></main>
}
