import { notFound } from 'next/navigation'
import { ArrowLeft, ArrowUpRight, Check, ChevronLeft, ChevronRight } from 'lucide-react'
import Link from 'next/link'
import { getVehicle } from '@/lib/vehicles'

export default async function VehicleDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const vehicle = getVehicle((await params).id)
  if (!vehicle) notFound()
  const gallery = vehicle.gallery.length ? vehicle.gallery : [vehicle.image]
  return <main className="vehicle-showroom"><div className="vehicle-showroom-nav"><Link href="/vehicules"><ArrowLeft size={16} /> Retour au stock</Link><span>PLANÈTE AUTO / RÉF. {vehicle.details?.find(([label]) => label === 'Référence')?.[1] ?? vehicle.id}</span></div><div className="vehicle-showroom-layout"><section className="vehicle-gallery"><div className="vehicle-main-photo"><img src={gallery[0]} alt={`${vehicle.name} ${vehicle.meta}`} /><button aria-label="Photo précédente"><ChevronLeft /></button><button aria-label="Photo suivante"><ChevronRight /></button><span className="photo-count">01 / {String(gallery.length).padStart(2, '0')}</span></div><div className="vehicle-thumbnails">{gallery.map((image, index) => <img key={image} src={image} alt={`${vehicle.name}, photo ${index + 1}`} />)}</div></section><aside className="vehicle-purchase"><span className="vehicle-status">{vehicle.status}</span><h1>{vehicle.name}</h1><p className="vehicle-version">{vehicle.meta}</p><div className="purchase-rule" /><strong className="showroom-price">{vehicle.price}</strong><p className="showroom-location">Saint-Jean-de-Védas · {vehicle.year} · {vehicle.km}</p><Link className="button button-red showroom-cta" href="/contact">Parler de ce véhicule <ArrowUpRight size={17} /></Link><div className="showroom-trust"><Check size={18} /><span>Véhicule contrôlé et préparé par Planète Auto</span></div></aside></div><section className="vehicle-facts"><div className="vehicle-facts-heading"><span className="eyebrow"><span className="eyebrow-line" /> Fiche technique</span><h2>Les détails qui<br /><em>font la différence.</em></h2></div><div className="facts-grid">{vehicle.details?.map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="vehicle-description"><span className="card-kicker">L'histoire du véhicule</span><h2>Une occasion qui mérite<br />votre attention.</h2><p>Audi A5 Cabriolet 3.0 V6 TDI 245ch S line quattro S tronic 7, coupé gris, 4 places, intérieur cuir et alcantara. Un véhicule entretenu et préparé avec soin par Planète Auto.</p></div></section></main>
}
